seed: 42
model_name: microsoft/mdeberta-v3-base
max_length: 256
batch_size: 16
num_epochs: 5
dropout: 0.2
classifier_lr: 2.0e-5
encoder_lr: 1.0e-5
mdeberta_tunable_layers: 2
weight_decay: 0.01
warmup_ratio: 0.1
grad_clip_norm: 0.5
long_text_threshold: 450
min_chunk_length: 50
log_root: runs/task7
checkpoint_root: checkpoints/task7
checkpoint_path: checkpoints/task7/article_style/mdeberta_processed_article/best_model.pt
train_path: SemEval2024-task8/subtaskA/data/subtaskA_train_multilingual.jsonl
dev_path: SemEval2024-task8/subtaskA/data/subtaskA_dev_multilingual.jsonl
